package org.cloudburstmc.protocol.java.codec.v754;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import org.cloudburstmc.protocol.common.util.TypeMap;
import org.cloudburstmc.protocol.java.codec.JavaCodec;
import org.cloudburstmc.protocol.java.codec.v754.serializer.handshake.HandshakingSerializer_v754;
import org.cloudburstmc.protocol.java.codec.v754.serializer.login.*;
import org.cloudburstmc.protocol.java.codec.v754.serializer.play.*;
import org.cloudburstmc.protocol.java.codec.v754.serializer.play.clientbound.*;
import org.cloudburstmc.protocol.java.codec.v754.serializer.play.serverbound.*;
import org.cloudburstmc.protocol.java.codec.v754.serializer.status.PingSerializer_v754;
import org.cloudburstmc.protocol.java.codec.v754.serializer.status.PongSerializer_v754;
import org.cloudburstmc.protocol.java.codec.v754.serializer.status.StatusRequestSerializer_v754;
import org.cloudburstmc.protocol.java.codec.v754.serializer.status.StatusResponseSerializer_v754;
import org.cloudburstmc.protocol.java.data.entity.EntityDataType;
import org.cloudburstmc.protocol.java.data.entity.EntityType;
import org.cloudburstmc.protocol.java.data.entity.MobEffectType;
import org.cloudburstmc.protocol.java.data.entity.Pose;
import org.cloudburstmc.protocol.java.data.inventory.ContainerType;
import org.cloudburstmc.protocol.java.data.world.BlockEntityAction;
import org.cloudburstmc.protocol.java.data.world.ParticleType;
import org.cloudburstmc.protocol.java.packet.State;
import org.cloudburstmc.protocol.java.packet.handshake.HandshakingPacket;
import org.cloudburstmc.protocol.java.packet.login.*;
import org.cloudburstmc.protocol.java.packet.play.*;
import org.cloudburstmc.protocol.java.packet.play.clientbound.*;
import org.cloudburstmc.protocol.java.packet.play.serverbound.*;
import org.cloudburstmc.protocol.java.packet.status.PingPacket;
import org.cloudburstmc.protocol.java.packet.status.PongPacket;
import org.cloudburstmc.protocol.java.packet.status.StatusRequestPacket;
import org.cloudburstmc.protocol.java.packet.status.StatusResponsePacket;

import static org.cloudburstmc.protocol.java.data.entity.EntityDataType.*;
import static org.cloudburstmc.protocol.java.data.entity.EntityType.*;
import static org.cloudburstmc.protocol.java.data.entity.MobEffectType.*;
import static org.cloudburstmc.protocol.java.data.entity.Pose.*;
import static org.cloudburstmc.protocol.java.data.inventory.ContainerType.*;
import static org.cloudburstmc.protocol.java.data.world.BlockEntityAction.*;
import static org.cloudburstmc.protocol.java.data.world.ParticleType.*;

@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Java_v754 {
    
    protected static final TypeMap<EntityType> ENTITY_TYPES = TypeMap.builder(EntityType.class)
            .insert(0, AREA_EFFECT_CLOUD)
            .insert(1, ARMOR_STAND)
            .insert(2, ARROW)
            .insert(3, BAT)
            .insert(4, BEE)
            .insert(5, BOAT)
            .insert(6, BLAZE)
            .insert(7, CAT)
            .insert(8, CAVE_SPIDER)
            .insert(9, CHICKEN)
            .insert(10, COD)
            .insert(11, COW)
            .insert(12, CREEPER)
            .insert(13, DONKEY)
            .insert(14, EntityType.DOLPHIN)
            .insert(15, DRAGON_FIREBALL)
            .insert(16, DROWNED)
            .insert(17, EntityType.ELDER_GUARDIAN)
            .insert(18, END_CRYSTAL)
            .insert(19, ENDER_DRAGON)
            .insert(20, ENDERMAN)
            .insert(21, ENDERMITE)
            .insert(22, EVOKER_FANGS)
            .insert(23, EVOKER)
            .insert(24, EXPERIENCE_ORB)
            .insert(25, EYE_OF_ENDER)
            .insert(26, FALLING_BLOCK)
            .insert(27, FIREWORK_ROCKET)
            .insert(28, FOX)
            .insert(29, GHAST)
            .insert(30, GIANT)
            .insert(31, GUARDIAN)
            .insert(32, HORSE)
            .insert(33, HUSK)
            .insert(34, ILLUSIONER)
            .insert(35, EntityType.ITEM)
            .insert(36, ITEM_FRAME)
            .insert(37, FIREBALL)
            .insert(38, LEASH_KNOT)
            .insert(39, LIGHTNING_BOLT)
            .insert(40, LLAMA)
            .insert(41, LLAMA_SPIT)
            .insert(42, MAGMA_CUBE)
            .insert(43, MINECART)
            .insert(44, MINECART_CHEST)
            .insert(45, MINECART_COMMAND_BLOCK)
            .insert(46, MINECART_FURNACE)
            .insert(47, MINECART_HOPPER)
            .insert(48, MINECART_SPAWNER)
            .insert(49, MINECART_TNT)
            .insert(50, MULE)
            .insert(51, MOOSHROOM)
            .insert(52, OCELOT)
            .insert(53, PAINTING)
            .insert(54, PANDA)
            .insert(55, PARROT)
            .insert(56, PIG)
            .insert(57, PIGLIN)
            .insert(58, PIGLIN_BRUTE)
            .insert(59, PUFFERFISH)
            .insert(60, POLAR_BEAR)
            .insert(61, PRIMED_TNT)
            .insert(62, RABBIT)
            .insert(63, SALMON)
            .insert(64, SHEEP)
            .insert(65, SHULKER)
            .insert(66, SHULKER_BULLET)
            .insert(67, SILVERFISH)
            .insert(68, SKELETON)
            .insert(69, SKELETON_HORSE)
            .insert(70, SLIME)
            .insert(71, SMALL_FIREBALL)
            .insert(72, SNOW_GOLEM)
            .insert(73, SNOWBALL)
            .insert(74, SPECTRAL_ARROW)
            .insert(75, SPIDER)
            .insert(76, SQUID)
            .insert(77, STRAY)
            .insert(78, TRADER_LLAMA)
            .insert(79, TROPICAL_FISH)
            .insert(80, TURTLE)
            .insert(81, THROWN_EGG)
            .insert(82, THROWN_ENDERPEARL)
            .insert(83, THROWN_EXP_BOTTLE)
            .insert(84, THROWN_POTION)
            .insert(85, TRIDENT)
            .insert(86, VEX)
            .insert(87, VILLAGER)
            .insert(88, IRON_GOLEM)
            .insert(89, VINDICATOR)
            .insert(90, PILLAGER)
            .insert(91, WANDERING_TRADER)
            .insert(92, EntityType.WITCH)
            .insert(93, EntityType.WITHER)
            .insert(94, WITHER_SKELETON)
            .insert(95, WITHER_SKULL)
            .insert(96, WOLF)
            .insert(97, ZOMBIE)
            .insert(98, ZOMBIE_HORSE)
            .insert(99, ZOMBIFIED_PIGLIN)
            .insert(100, ZOMBIE_VILLAGER)
            .insert(101, PHANTOM)
            .insert(102, RAVAGER)
            .insert(103, HOGLIN)
            .insert(104, STRIDER)
            .insert(105, ZOGLIN)
            .insert(106, PLAYER)
            .insert(107, FISHING_BOBBER)
            .build();
    
    protected static final TypeMap<BlockEntityAction> BLOCK_ENTITY_ACTIONS = TypeMap.builder(BlockEntityAction.class)
            .insert(1, MOB_SPAWNER_DATA)
            .insert(2, COMMAND_BLOCK_TEXT)
            .insert(3, BEACON_LEVEL)
            .insert(4, HEAD_ROTATION)
            .insert(5, DECLARE_CONDUIT)
            .insert(6, BANNER_COLOR)
            .insert(7, STRUCTURE_DATA)
            .insert(8, GATEWAY_DESTINATION)
            .insert(9, SIGN_TEXT)
            .insert(11, DECLARE_BED)
            .insert(12, JIGSAW_DATA)
            .insert(13, CAMPFIRE_ITEMS)
            .insert(14, BEEHIVE_INFO)
            .build();
    
    protected static final TypeMap<ContainerType> CONTAINER_TYPES = TypeMap.builder(ContainerType.class)
            .insert(0, GENERIC_9X1)
            .insert(1, GENERIC_9X2)
            .insert(2, GENERIC_9X3)
            .insert(3, GENERIC_9X4)
            .insert(4, GENERIC_9X5)
            .insert(5, GENERIC_9X6)
            .insert(6, GENERIC_3X3)
            .insert(7, ANVIL)
            .insert(8, BEACON)
            .insert(9, BLAST_FURNACE)
            .insert(10, BREWING_STAND)
            .insert(11, CRAFTING)
            .insert(12, ENCHANTMENT)
            .insert(13, FURNACE)
            .insert(14, GRINDSTONE)
            .insert(15, HOPPER)
            .insert(16, LECTERN)
            .insert(17, LOOM)
            .insert(18, MERCHANT)
            .insert(19, SHULKER_BOX)
            .insert(20, SMITHING)
            .insert(21, SMOKER)
            .insert(22, CARTOGRAPHY_TABLE)
            .insert(23, STONECUTTER)
            .build();
    
    protected static final TypeMap<EntityDataType<?>> ENTITY_DATA_TYPES = TypeMap.<EntityDataType<?>>builder("EntityDataType")
            .insert(0, BYTE)
            .insert(1, INT)
            .insert(2, FLOAT)
            .insert(3, STRING)
            .insert(4, COMPONENT)
            .insert(5, OPTIONAL_COMPONENT)
            .insert(6, ITEM_STACK)
            .insert(7, BOOLEAN)
            .insert(8, ROTATION)
            .insert(9, BLOCK_POS)
            .insert(10, OPTIONAL_BLOCK_POS)
            .insert(11, DIRECTION)
            .insert(12, OPTIONAL_UUID)
            .insert(13, OPTIONAL_BLOCK_STATE)
            .insert(14, NBT)
            .insert(15, PARTICLE)
            .insert(16, VILLAGER_DATA)
            .insert(17, OPTIONAL_INT)
            .insert(18, POSE)
            .build();
    
    protected static final TypeMap<Pose> POSES = TypeMap.builder(Pose.class)
            .insert(0, STANDING)
            .insert(1, FALL_FLYING)
            .insert(2, SLEEPING)
            .insert(3, SWIMMING)
            .insert(4, SPIN_ATTACK)
            .insert(5, CROUCHING)
            .insert(6, DYING)
            .build();
    
    protected static final TypeMap<ParticleType> PARTICLES = TypeMap.builder(ParticleType.class)
            .insert(0, AMBIENT_ENTITY_EFFECT)
            .insert(1, ANGRY_VILLAGER)
            .insert(2, BARRIER)
            .insert(3, BLOCK)
            .insert(4, BUBBLE)
            .insert(5, CLOUD)
            .insert(6, CRIT)
            .insert(7, DAMAGE_INDICATOR)
            .insert(8, DRAGON_BREATH)
            .insert(9, DRIPPING_LAVA)
            .insert(10, FALLING_LAVA)
            .insert(11, LANDING_LAVA)
            .insert(12, DRIPPING_WATER)
            .insert(13, FALLING_WATER)
            .insert(14, DUST)
            .insert(15, EFFECT)
            .insert(16, ParticleType.ELDER_GUARDIAN)
            .insert(17, ENCHANTED_HIT)
            .insert(18, ENCHANT)
            .insert(19, END_ROD)
            .insert(20, ENTITY_EFFECT)
            .insert(21, EXPLOSION_EMITTER)
            .insert(22, EXPLOSION)
            .insert(23, FALLING_DUST)
            .insert(24, FIREWORK)
            .insert(25, FISHING)
            .insert(26, FLAME)
            .insert(27, SOUL_FLAME)
            .insert(28, SOUL)
            .insert(29, FLASH)
            .insert(30, HAPPY_VILLAGER)
            .insert(31, COMPOSTER)
            .insert(32, HEART)
            .insert(33, INSTANT_EFFECT)
            .insert(34, ParticleType.ITEM)
            .insert(35, ITEM_SLIME)
            .insert(36, ITEM_SNOWBALL)
            .insert(37, LARGE_SMOKE)
            .insert(38, LAVA)
            .insert(39, MYCELIUM)
            .insert(40, NOTE)
            .insert(41, POOF)
            .insert(42, PORTAL)
            .insert(43, RAIN)
            .insert(44, SMOKE)
            .insert(45, SNEEZE)
            .insert(46, SPIT)
            .insert(47, SQUID_INK)
            .insert(48, SWEEP_ATTACK)
            .insert(49, TOTEM_OF_UNDYING)
            .insert(50, UNDERWATER)
            .insert(51, SPLASH)
            .insert(52, ParticleType.WITCH)
            .insert(53, BUBBLE_POP)
            .insert(54, CURRENT_DOWN)
            .insert(55, BUBBLE_COLUMN_UP)
            .insert(56, NAUTILUS)
            .insert(57, ParticleType.DOLPHIN)
            .insert(58, CAMPFIRE_COSY_SMOKE)
            .insert(59, CAMPFIRE_SIGNAL_SMOKE)
            .insert(60, DRIPPING_HONEY)
            .insert(61, FALLING_HONEY)
            .insert(62, LANDING_HONEY)
            .insert(63, FALLING_NECTAR)
            .insert(64, ASH)
            .insert(65, CRIMSON_SPORE)
            .insert(66, WARPED_SPORE)
            .insert(67, DRIPPING_OBSIDIAN_TEAR)
            .insert(68, FALLING_OBSIDIAN_TEAR)
            .insert(69, LANDING_OBSIDIAN_TEAR)
            .insert(70, REVERSE_PORTAL)
            .insert(71, WHITE_ASH)
            .build();
    
    protected static final TypeMap<MobEffectType> MOB_EFFECTS = TypeMap.builder(MobEffectType.class)
            .insert(1, SPEED)
            .insert(2, SLOWNESS)
            .insert(3, HASTE)
            .insert(4, MINING_FATIGUE)
            .insert(5, STRENGTH)
            .insert(6, INSTANT_HEALTH)
            .insert(7, INSTANT_DAMAGE)
            .insert(8, JUMP_BOOST)
            .insert(9, NAUSEA)
            .insert(10, REGENERATION)
            .insert(11, DAMAGE_RESISTANCE)
            .insert(12, FIRE_RESISTANCE)
            .insert(13, WATER_BREATHING)
            .insert(14, INVISIBILITY)
            .insert(15, BLINDNESS)
            .insert(16, NIGHT_VISION)
            .insert(17, HUNGER)
            .insert(18, WEAKNESS)
            .insert(19, POISON)
            .insert(20, MobEffectType.WITHER)
            .insert(21, HEALTH_BOOST)
            .insert(22, ABSORPTION)
            .insert(23, SATURATION)
            .insert(24, GLOWING)
            .insert(25, LEVITATION)
            .insert(26, LUCK)
            .insert(27, UNLUCK)
            .insert(28, SLOW_FALLING)
            .insert(29, CONDUIT_POWER)
            .insert(30, DOLPHINS_GRACE)
            .insert(31, BAD_OMEN)
            .insert(32, HERO_OF_THE_VILLAGE)
            .build();

    public static final JavaCodec V754_CODEC = JavaCodec.builder()
            .protocolVersion(754)
            .minecraftVersion("1.16.4/5")
            .helper(() -> new JavaCodecHelper_v754(ENTITY_TYPES, BLOCK_ENTITY_ACTIONS, CONTAINER_TYPES, ENTITY_DATA_TYPES, POSES, PARTICLES, MOB_EFFECTS))
            .codec(State.HANDSHAKING, JavaCodec.JavaStateCodec.builder()
                    .registerServerboundPacket(HandshakingPacket.class, HandshakingSerializer_v754.INSTANCE, 0)
                    // .registerClientboundPacket(LegacyServerListPingPacket.class, LegacyServerListPingSerializer_v754.INSTANCE, 254) // TODO
                    .build())
            .codec(State.STATUS, JavaCodec.JavaStateCodec.builder()
                    .registerClientboundPacket(StatusResponsePacket.class, StatusResponseSerializer_v754.INSTANCE, 0)
                    .registerClientboundPacket(PongPacket.class, PongSerializer_v754.INSTANCE, 1)
                    .registerServerboundPacket(StatusRequestPacket.class, StatusRequestSerializer_v754.INSTANCE, 0)
                    .registerServerboundPacket(PingPacket.class, PingSerializer_v754.INSTANCE, 1)
                    .build())
            .codec(State.LOGIN, JavaCodec.JavaStateCodec.builder()
                    .registerClientboundPacket(org.cloudburstmc.protocol.java.packet.login.DisconnectPacket.class, org.cloudburstmc.protocol.java.codec.v754.serializer.login.DisconnectSerializer_v754.INSTANCE, 0)
                    .registerClientboundPacket(EncryptionRequestPacket.class, EncryptionRequestSerializer_v754.INSTANCE, 1)
                    .registerClientboundPacket(LoginSuccessPacket.class, LoginSuccessSerializer_v754.INSTANCE, 2)
                    .registerClientboundPacket(SetCompressionPacket.class, SetCompressionSerializer_v754.INSTANCE, 3)
                    .registerClientboundPacket(CustomQueryRequestPacket.class, CustomQueryRequestSerializer_v754.INSTANCE, 4)
                    .registerServerboundPacket(LoginStartPacket.class, LoginStartSerializer_v754.INSTANCE, 0)
                    .registerServerboundPacket(EncryptionResponsePacket.class, EncryptionResponseSerializer_v754.INSTANCE, 1)
                    .registerServerboundPacket(CustomQueryResponsePacket.class, CustomQueryResponseSerializer_v754.INSTANCE, 2)
                    .build())
            .codec(State.PLAY, JavaCodec.JavaStateCodec.builder()
                    .registerClientboundPacket(AddEntityPacket.class, AddEntitySerializer_v754.INSTANCE, 0)
                    .registerClientboundPacket(AddExperienceOrbPacket.class, AddExperienceOrbSerializer_v754.INSTANCE, 1)
                    .registerClientboundPacket(AddMobPacket.class, AddMobSerializer_v754.INSTANCE, 2)
                    .registerClientboundPacket(AddPaintingPacket.class, AddPaintingSerializer_v754.INSTANCE, 3)
                    .registerClientboundPacket(AddPlayerPacket.class, AddPlayerSerializer_v754.INSTANCE, 4)
                    .registerClientboundPacket(AnimatePacket.class, AnimateSerializer_v754.INSTANCE, 5)
                    .registerClientboundPacket(AwardStatsPacket.class, AwardStatsSerializer_v754.INSTANCE, 6)
                    .registerClientboundPacket(BlockBreakAckPacket.class, BlockBreakAckSerializer_v754.INSTANCE, 7)
                    .registerClientboundPacket(BlockDestructionPacket.class, BlockDestructionSerializer_v754.INSTANCE, 8)
                    .registerClientboundPacket(BlockEntityDataPacket.class, BlockEntityDataSerializer_v754.INSTANCE, 9)
                    .registerClientboundPacket(BlockEventPacket.class, BlockEventSerializer_v754.INSTANCE, 10)
                    .registerClientboundPacket(BlockUpdatePacket.class, BlockUpdateSerializer_v754.INSTANCE, 11)
                    .registerClientboundPacket(BossEventPacket.class, BossEventSerializer_v754.INSTANCE, 12)
                    .registerClientboundPacket(ChangeDifficultyPacket.class, ChangeDifficultySerializer_v754.INSTANCE, 13)
                    .registerClientboundPacket(ChatPacket.class, ChatSerializer_v754.INSTANCE, 14)
                    .registerClientboundPacket(CommandSuggestionsPacket.class, CommandSuggestionsSerializer_v754.INSTANCE, 15)
                    .registerClientboundPacket(CommandsPacket.class, CommandsSerializer_v754.INSTANCE, 16)
                    .registerClientboundPacket(ContainerAckPacket.class, ContainerAckSerializer_v754.INSTANCE, 17)
                    .registerClientboundPacket(ContainerClosePacket.class, ContainerCloseSerializer_v754.INSTANCE, 18)
                    .registerClientboundPacket(ContainerSetContentPacket.class, ContainerSetContentSerializer_v754.INSTANCE, 19)
                    .registerClientboundPacket(ContainerSetDataPacket.class, ContainerSetDataSerializer_v754.INSTANCE, 20)
                    .registerClientboundPacket(ContainerSetSlotPacket.class, ContainerSetSlotSerializer_v754.INSTANCE, 21)
                    .registerClientboundPacket(CooldownPacket.class, CooldownSerializer_v754.INSTANCE, 22)
                    .registerClientboundPacket(CustomPayloadPacket.class, CustomPayloadSerializer_v754.INSTANCE, 23)
                    .registerClientboundPacket(CustomSoundPacket.class, CustomSoundSerializer_v754.INSTANCE, 24)
                    .registerClientboundPacket(org.cloudburstmc.protocol.java.packet.play.clientbound.DisconnectPacket.class, org.cloudburstmc.protocol.java.codec.v754.serializer.play.clientbound.DisconnectSerializer_v754.INSTANCE, 25)
                    .registerClientboundPacket(EntityEventPacket.class, EntityEventSerializer_v754.INSTANCE, 26)
                    .registerClientboundPacket(ExplodePacket.class, ExplodeSerializer_v754.INSTANCE, 27)
                    .registerClientboundPacket(ForgetLevelChunkPacket.class, ForgetLevelChunkSerializer_v754.INSTANCE, 28)
                    .registerClientboundPacket(GameEventPacket.class, GameEventSerializer_v754.INSTANCE, 29)
                    .registerClientboundPacket(HorseScreenOpenPacket.class, HorseScreenOpenSerializer_v754.INSTANCE, 30)
                    .registerClientboundPacket(KeepAlivePacket.class, KeepAliveSerializer_v754.INSTANCE, 31)
                    .registerClientboundPacket(LevelChunkPacket.class, LevelChunkSerializer_v754.INSTANCE, 32)
                    .registerClientboundPacket(LevelEventPacket.class, LevelEventSerializer_v754.INSTANCE, 33)
                    .registerClientboundPacket(LevelParticlesPacket.class, LevelParticlesSerializer_v754.INSTANCE, 34)
                    .registerClientboundPacket(LightUpdatePacket.class, LightUpdateSerializer_v754.INSTANCE, 35)
                    .registerClientboundPacket(LoginPacket.class, LoginSerializer_v754.INSTANCE, 36)
                    .registerClientboundPacket(MapItemDataPacket.class, MapItemDataSerializer_v754.INSTANCE, 37)
                    .registerClientboundPacket(MerchantOffersPacket.class, MerchantOffersSerializer_v754.INSTANCE, 38)
                    .registerClientboundPacket(MoveEntityPacket.Pos.class, MoveEntitySerializer_v754.Pos.INSTANCE, 39)
                    .registerClientboundPacket(MoveEntityPacket.PosRot.class, MoveEntitySerializer_v754.PosRot.INSTANCE, 40)
                    .registerClientboundPacket(MoveEntityPacket.Rot.class, MoveEntitySerializer_v754.Rot.INSTANCE, 41)
                    .registerClientboundPacket(MoveEntityPacket.class, MoveEntitySerializer_v754.Noop.INSTANCE, 42)
                    .registerClientboundPacket(MoveVehiclePacket.class, MoveVehicleSerializer_v754.INSTANCE, 43)
                    .registerClientboundPacket(OpenBookPacket.class, OpenBookSerializer_v754.INSTANCE, 44)
                    .registerClientboundPacket(OpenScreenPacket.class, OpenScreenSerializer_v754.INSTANCE, 45)
                    .registerClientboundPacket(OpenSignEditorPacket.class, OpenSignEditorSerializer_v754.INSTANCE, 46)
                    .registerClientboundPacket(PlaceGhostRecipePacket.class, PlaceGhostRecipeSerializer_v754.INSTANCE, 47)
                    .registerClientboundPacket(PlayerAbilitiesPacket.class, PlayerAbilitiesSerializer_v754.INSTANCE, 48)
                    .registerClientboundPacket(PlayerCombatPacket.class, PlayerCombatSerializer_v754.INSTANCE, 49)
                    .registerClientboundPacket(PlayerInfoPacket.class, PlayerInfoSerializer_v754.INSTANCE, 50)
                    .registerClientboundPacket(PlayerLookAtPacket.class, PlayerLookAtSerializer_v754.INSTANCE, 51)
                    .registerClientboundPacket(PlayerPositionPacket.class, PlayerPositionSerializer_v754.INSTANCE, 52)
                    .registerClientboundPacket(RecipePacket.class, RecipeSerializer_v754.INSTANCE, 53)
                    .registerClientboundPacket(RemoveEntitiesPacket.class, RemoveEntitiesSerializer_v754.INSTANCE, 54)
                    .registerClientboundPacket(RemoveMobEffectPacket.class, RemoveMobEffectSerializer_v754.INSTANCE, 55)
                    .registerClientboundPacket(ResourcePackPacket.class, ResourcePackSerializer_v754.INSTANCE, 56)
                    .registerClientboundPacket(RespawnPacket.class, RespawnSerializer_v754.INSTANCE, 57)
                    .registerClientboundPacket(RotateHeadPacket.class, RotateHeadSerializer_v754.INSTANCE, 58)
                    .registerClientboundPacket(SectionBlocksUpdatePacket.class, SectionBlocksUpdateSerializer_v754.INSTANCE, 59)
                    .registerClientboundPacket(SelectAdvancementsTabPacket.class, SelectAdvancementsTabSerializer_v754.INSTANCE, 60)
                    .registerClientboundPacket(SetBorderPacket.class, SetBorderSerializer_v754.INSTANCE, 61)
                    .registerClientboundPacket(SetCameraPacket.class, SetCameraSerializer_v754.INSTANCE, 62)
                    .registerClientboundPacket(SetCarriedItemPacket.class, SetCarriedItemSerializer_v754.INSTANCE, 63)
                    .registerClientboundPacket(SetChunkCacheCenterPacket.class, SetChunkCacheCenterSerializer_v754.INSTANCE, 64)
                    .registerClientboundPacket(SetChunkCacheRadiusPacket.class, SetChunkCacheRadiusSerializer_v754.INSTANCE, 65)
                    .registerClientboundPacket(SetDefaultSpawnPositionPacket.class, SetDefaultSpawnPositionSerializer_v754.INSTANCE, 66)
                    .registerClientboundPacket(SetDisplayObjectivePacket.class, SetDisplayObjectiveSerializer_v754.INSTANCE, 67)
                    .registerClientboundPacket(SetEntityDataPacket.class, SetEntityDataSerializer_v754.INSTANCE, 68)
                    .registerClientboundPacket(SetEntityLinkPacket.class, SetEntityLinkSerializer_v754.INSTANCE, 69)
                    .registerClientboundPacket(SetEntityMotionPacket.class, SetEntityMotionSerializer_v754.INSTANCE, 70)
                    .registerClientboundPacket(SetEquipmentPacket.class, SetEquipmentSerializer_v754.INSTANCE, 71)
                    .registerClientboundPacket(SetExperiencePacket.class, SetExperienceSerializer_v754.INSTANCE, 72)
                    .registerClientboundPacket(SetHealthPacket.class, SetHealthSerializer_v754.INSTANCE, 73)
                    .registerClientboundPacket(SetObjectivePacket.class, SetObjectiveSerializer_v754.INSTANCE, 74)
                    .registerClientboundPacket(SetPassengersPacket.class, SetPassengersSerializer_v754.INSTANCE, 75)
                    .registerClientboundPacket(SetPlayerTeamPacket.class, SetPlayerTeamSerializer_v754.INSTANCE, 76)
                    .registerClientboundPacket(SetScorePacket.class, SetScoreSerializer_v754.INSTANCE, 77)
                    .registerClientboundPacket(SetTimePacket.class, SetTimeSerializer_v754.INSTANCE, 78)
                    .registerClientboundPacket(SetTitlesPacket.class, SetTitlesSerializer_v754.INSTANCE, 79)
                    .registerClientboundPacket(SoundEntityPacket.class, SoundEntitySerializer_v754.INSTANCE, 80)
                    .registerClientboundPacket(SoundPacket.class, SoundSerializer_v754.INSTANCE, 81)
                    .registerClientboundPacket(StopSoundPacket.class, StopSoundSerializer_v754.INSTANCE, 82)
                    .registerClientboundPacket(TabListPacket.class, TabListSerializer_v754.INSTANCE, 83)
                    .registerClientboundPacket(TagQueryPacket.class, TagQuerySerializer_v754.INSTANCE, 84)
                    .registerClientboundPacket(TakeItemEntityPacket.class, TakeItemEntitySerializer_v754.INSTANCE, 85)
                    .registerClientboundPacket(TeleportEntityPacket.class, TeleportEntitySerializer_v754.INSTANCE, 86)
                    .registerClientboundPacket(UpdateAdvancementsPacket.class, UpdateAdvancementsSerializer_v754.INSTANCE, 87)
                    .registerClientboundPacket(UpdateAttributesPacket.class, UpdateAttributesSerializer_v754.INSTANCE, 88)
                    .registerClientboundPacket(UpdateMobEffectPacket.class, UpdateMobEffectSerializer_v754.INSTANCE, 89)
                    .registerClientboundPacket(UpdateRecipesPacket.class, UpdateRecipesSerializer_v754.INSTANCE, 90)
                    .registerClientboundPacket(UpdateTagsPacket.class, UpdateTagsSerializer_v754.INSTANCE, 91)

                    .registerServerboundPacket(AcceptTeleportationPacket.class, AcceptTeleportationSerializer_v754.INSTANCE, 0)
                    .registerServerboundPacket(BlockEntityTagQueryPacket.class, BlockEntityTagQuerySerializer_v754.INSTANCE, 1)
                    .registerServerboundPacket(ChangeDifficultyPacket.class, ChangeDifficultySerializer_v754.INSTANCE, 2)
                    .registerServerboundPacket(ChatPacket.class, ChatSerializer_v754.INSTANCE, 3)
                    .registerServerboundPacket(ClientCommandPacket.class, ClientCommandSerializer_v754.INSTANCE, 4)
                    .registerServerboundPacket(ClientInformationPacket.class, ClientInformationSerializer_v754.INSTANCE, 5)
                    .registerServerboundPacket(CommandSuggestionPacket.class, CommandSuggestionSerializer_v754.INSTANCE, 6)
                    .registerServerboundPacket(ContainerAckPacket.class, ContainerAckSerializer_v754.INSTANCE, 7)
                    .registerServerboundPacket(ContainerButtonClickPacket.class, ContainerButtonClickSerializer_754.INSTANCE, 8)
                    .registerServerboundPacket(ContainerClickPacket.class, ContainerClickSerializer_v754.INSTANCE, 9)
                    .registerServerboundPacket(ContainerClosePacket.class, ContainerCloseSerializer_v754.INSTANCE, 10)
                    .registerServerboundPacket(CustomPayloadPacket.class, CustomPayloadSerializer_v754.INSTANCE, 11)
                    .registerServerboundPacket(EditBookPacket.class, EditBookSerializer_v754.INSTANCE, 12)
                    .registerServerboundPacket(EntityTagQueryPacket.class, EntityTagQuerySerializer_v754.INSTANCE, 13)
                    .registerServerboundPacket(InteractPacket.class, InteractSerializer_v754.INSTANCE, 14)
                    .registerServerboundPacket(JigsawGeneratePacket.class, JigsawGenerateSerializer_v754.INSTANCE, 15)
                    .registerServerboundPacket(KeepAlivePacket.class, KeepAliveSerializer_v754.INSTANCE, 16)
                    .registerServerboundPacket(LockDifficultyPacket.class, LockDifficultySerializer_v754.INSTANCE, 17)
                    .registerServerboundPacket(MovePlayerPacket.Pos.class, MovePlayerSerializer_v754.Pos.INSTANCE, 18)
                    .registerServerboundPacket(MovePlayerPacket.PosRot.class, MovePlayerSerializer_v754.PosRot.INSTANCE, 19)
                    .registerServerboundPacket(MovePlayerPacket.Rot.class, MovePlayerSerializer_v754.Rot.INSTANCE, 20)
                    .registerServerboundPacket(MovePlayerPacket.class, MovePlayerSerializer_v754.OnGround.INSTANCE, 21)
                    .registerServerboundPacket(MoveVehiclePacket.class, MoveVehicleSerializer_v754.INSTANCE, 22)
                    .registerServerboundPacket(PaddleBoatPacket.class, PaddleBoatSerializer_v754.INSTANCE, 23)
                    .registerServerboundPacket(PickItemPacket.class, PickItemSerializer_v754.INSTANCE, 24)
                    .registerServerboundPacket(PlaceRecipePacket.class, PlaceRecipeSerializer_v754.INSTANCE, 25)
                    .registerServerboundPacket(PlayerAbilitiesPacket.class, PlayerAbilitiesSerializer_v754.INSTANCE, 26)
                    .registerServerboundPacket(PlayerActionPacket.class, PlayerActionSerializer_v754.INSTANCE, 27)
                    .registerServerboundPacket(PlayerCommandPacket.class, PlayerCommandSerializer_v754.INSTANCE, 28)
                    .registerServerboundPacket(PlayerInputPacket.class, PlayerInputSerializer_v754.INSTANCE, 29)
                    .registerServerboundPacket(RecipeBookChangeSettingsPacket.class, RecipeBookChangeSettingsSerializer_v754.INSTANCE, 30)
                    .registerServerboundPacket(RecipeBookSeenRecipePacket.class, RecipeBookSeenRecipeSerializer_v754.INSTANCE, 31)
                    .registerServerboundPacket(RenameItemPacket.class, RenameItemSerializer_v754.INSTANCE, 32)
                    .registerServerboundPacket(ResourcePackPacket.class, ResourcePackSerializer_v754.INSTANCE, 33)
                    .registerServerboundPacket(SeenAdvancementsPacket.class, SeenAdvancementsSerializer_v754.INSTANCE, 34)
                    .registerServerboundPacket(SelectTradePacket.class, SelectTradeSerializer_v754.INSTANCE, 35)
                    .registerServerboundPacket(SetBeaconPacket.class, SetBeaconSerializer_v754.INSTANCE, 36)
                    .registerServerboundPacket(SetCarriedItemPacket.class, SetCarriedItemSerializer_v754.INSTANCE, 37)
                    .registerServerboundPacket(SetCommandBlockPacket.class, SetCommandBlockSerializer_v754.INSTANCE, 38)
                    .registerServerboundPacket(SetCommandMinecartPacket.class, SetCommandMinecartSerializer_v754.INSTANCE, 39)
                    .registerServerboundPacket(SetCreativeModeSlotPacket.class, SetCreativeModeSlotSerializer_v754.INSTANCE, 40)
                    .registerServerboundPacket(SetJigsawBlockPacket.class, SetJigsawBlockSerializer_v754.INSTANCE, 41)
                    .registerServerboundPacket(SetStructureBlockPacket.class, SetStructureBlockSerializer_v754.INSTANCE, 42)
                    .registerServerboundPacket(SignUpdatePacket.class, SignUpdateSerializer_v754.INSTANCE, 43)
                    .registerServerboundPacket(SwingPacket.class, SwingPacketSerializer_v754.INSTANCE, 44)
                    .registerServerboundPacket(TeleportToEntityPacket.class, TeleportToEntitySerializer_v754.INSTANCE, 45)
                    .registerServerboundPacket(UseItemOnPacket.class, UseItemOnSerializer_v754.INSTANCE, 46)
                    .registerServerboundPacket(UseItemPacket.class, UseItemSerializer_v754.INSTANCE, 47)
                    .build())
            .build();
}
